### ISSUE TITLE
Is it expected that LSP instance is started for every KCL buffer ?

### ISSUE THREAD

**Issue by eshepelyuk** [kcl-lang/vim-kcl#10]
### Opening KCL files

When I open a single file 

```
nvim file1.k
```

the `kcl-language-server` instance is started, then I'm opening another split in the same NeoVim instance with command 

```
:vs file2.k
```

and I see that 2nd instance of `kcl-language-server` is started. Is it expected behavior ?

### Closing KCL files

When I close either `file1.k` or `file2.k` - both instances of `kcl-language-server` keep running.
and they are shut down only on exiting NeoVim.

**Comment by Peefy** [comment]
cc @He1pa
