### ISSUE TITLE
Format tool error

### ISSUE THREAD

**Issue by He1pa** [kcl-lang/vim-kcl#14]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. auto fmt kcl in lunarvim
2. fmt result error

**Comment by Peefy** [comment]
Please provide more reliable information, it would be even better if there could be an example.

**Comment by He1pa** [comment]
![image](https://github.com/user-attachments/assets/665a3a24-483f-4e17-a86b-cd42ad56a6ba)
